//! Emergency range prior: load, verify, and query the precomputed equity table.
//!
//! The prior is a 4,320-entry flat f64 array generated by
//! `python/scripts/build_emergency_prior.py`.  It encodes approximate equity
//! for each (hand_bucket, board_texture, pot_class, aggressor_role, n_players)
//! combination against a typical opponent range.
//!
//! # Startup contract
//! Call `EmergencyRangePrior::load()` once at startup.  If it returns `Err`,
//! the caller **must not start** — no EMERGENCY fallback exists without the prior.

use artifact_store::{ArtifactManifest, IntegrityError, load_manifest, verify_artifact};
use engine_core::{BoardTexture, HandBucket};
use std::{fs, path::Path};
use thiserror::Error;

// ─── Table dimensions (must match build_emergency_prior.py) ──────────────────

pub const N_HAND_BUCKETS:    usize = 12;
pub const N_BOARD_TEXTURES:  usize = 6;
pub const N_POT_CLASSES:     usize = 4;
pub const N_AGGRESSOR_ROLES: usize = 3;
pub const N_PLAYER_BUCKETS:  usize = 5;

pub const TABLE_LEN: usize =
    N_HAND_BUCKETS * N_BOARD_TEXTURES * N_POT_CLASSES * N_AGGRESSOR_ROLES * N_PLAYER_BUCKETS;

const EXPECTED_VERSION: u32 = 1;

// ─── Dimension enums ─────────────────────────────────────────────────────────

/// Pot class index matching the Python build script.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum PotClassIdx {
    Limped = 0,
    Srp    = 1,
    ThreeBp = 2,
    FourBpOrSqueeze = 3,
}

/// Whether the last preflop aggressor was OOP, IP, or there was no aggressor.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum AggressorRole {
    None  = 0,
    Ip    = 1,
    Oop   = 2,
}

/// Maps n_players (2–6) to the bucket index 0–4.
pub fn n_players_to_bucket(n: u8) -> usize {
    (n.saturating_sub(2).min(4)) as usize
}

// ─── Error ───────────────────────────────────────────────────────────────────

#[derive(Debug, Error)]
pub enum PriorLoadError {
    #[error("integrity check failed: {0}")]
    Integrity(#[from] IntegrityError),

    #[error("I/O error reading prior: {0}")]
    Io(#[from] std::io::Error),

    #[error("table length mismatch: expected {expected} f64 entries, got {actual}")]
    LengthMismatch { expected: usize, actual: usize },

    #[error("value out of range at index {index}: {value}")]
    ValueOutOfRange { index: usize, value: f64 },

    #[error("manifest validation failed: {0}")]
    ManifestInvalid(String),
}

// ─── The prior itself ─────────────────────────────────────────────────────────

#[derive(Debug)]
pub struct EmergencyRangePrior {
    table: Vec<f64>,
}

impl EmergencyRangePrior {
    /// Load and verify the prior from disk.  Fail hard on any integrity failure.
    ///
    /// `bin_path` is the path to `emergency_range_prior.bin`.
    /// `manifest_path` is the path to `emergency_range_prior.manifest.json`.
    pub fn load(bin_path: &Path, manifest_path: &Path) -> Result<Self, PriorLoadError> {
        // Load + verify manifest
        let manifest = load_manifest(manifest_path)?;
        Self::validate_manifest_dimensions(&manifest)?;

        // Verify artifact integrity (checksum + version + size)
        verify_artifact(bin_path, &manifest, EXPECTED_VERSION)?;

        // Parse f64 array
        let bytes = fs::read(bin_path)?;
        let table = Self::parse_f64_le(&bytes)?;

        // Validate all values are in [0, 1]
        for (i, &v) in table.iter().enumerate() {
            if !(0.0..=1.0).contains(&v) {
                return Err(PriorLoadError::ValueOutOfRange { index: i, value: v });
            }
        }

        log::info!("emergency prior loaded: {} entries, checksum OK", TABLE_LEN);
        Ok(Self { table })
    }

    /// Query equity for the given dimensions.
    ///
    /// Returns a value in [0, 1].  Never panics — out-of-range indices are
    /// clamped so a bug in the caller degrades gracefully.
    pub fn lookup(
        &self,
        hand_bucket:    HandBucket,
        board_texture:  BoardTexture,
        pot_class:      PotClassIdx,
        aggressor_role: AggressorRole,
        n_players:      u8,
    ) -> f64 {
        let idx = Self::index(
            hand_bucket.index(),
            board_texture.index(),
            pot_class as usize,
            aggressor_role as usize,
            n_players_to_bucket(n_players),
        );
        // Clamp defensively — index() is deterministic but let's be safe.
        self.table[idx.min(TABLE_LEN - 1)]
    }

    // ── Internals ─────────────────────────────────────────────────────────────

    fn index(h: usize, t: usize, p: usize, a: usize, n: usize) -> usize {
        h * (N_BOARD_TEXTURES * N_POT_CLASSES * N_AGGRESSOR_ROLES * N_PLAYER_BUCKETS)
            + t * (N_POT_CLASSES * N_AGGRESSOR_ROLES * N_PLAYER_BUCKETS)
            + p * (N_AGGRESSOR_ROLES * N_PLAYER_BUCKETS)
            + a * N_PLAYER_BUCKETS
            + n
    }

    fn parse_f64_le(bytes: &[u8]) -> Result<Vec<f64>, PriorLoadError> {
        if bytes.len() % 8 != 0 {
            return Err(PriorLoadError::LengthMismatch {
                expected: TABLE_LEN,
                actual:   bytes.len() / 8,
            });
        }
        let values: Vec<f64> = bytes
            .chunks_exact(8)
            .map(|b| f64::from_le_bytes(b.try_into().unwrap()))
            .collect();
        if values.len() != TABLE_LEN {
            return Err(PriorLoadError::LengthMismatch {
                expected: TABLE_LEN,
                actual:   values.len(),
            });
        }
        Ok(values)
    }

    fn validate_manifest_dimensions(m: &ArtifactManifest) -> Result<(), PriorLoadError> {
        let check = |field: &str, got: Option<usize>, expected: usize| {
            match got {
                None => Err(PriorLoadError::ManifestInvalid(format!("missing field: {field}"))),
                Some(v) if v != expected => Err(PriorLoadError::ManifestInvalid(format!(
                    "{field}: expected {expected}, got {v}"
                ))),
                _ => Ok(()),
            }
        };
        check("n_hand_buckets",    m.n_hand_buckets,    N_HAND_BUCKETS)?;
        check("n_board_textures",  m.n_board_textures,  N_BOARD_TEXTURES)?;
        check("n_pot_classes",     m.n_pot_classes,     N_POT_CLASSES)?;
        check("n_aggressor_roles", m.n_aggressor_roles, N_AGGRESSOR_ROLES)?;
        check("n_player_buckets",  m.n_player_buckets,  N_PLAYER_BUCKETS)?;
        Ok(())
    }
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use engine_core::{BoardTexture, HandBucket};
    use tempfile::tempdir;

    /// Build a minimal valid prior in a temp dir and return the dir + paths.
    fn build_test_prior() -> (tempfile::TempDir, std::path::PathBuf, std::path::PathBuf) {
        use artifact_store::checksum_bytes;

        let dir = tempdir().unwrap();
        let bin_path      = dir.path().join("emergency_range_prior.bin");
        let manifest_path = dir.path().join("emergency_range_prior.manifest.json");

        // Build a simple valid table (all entries = 0.5)
        let data: Vec<u8> = (0..TABLE_LEN)
            .flat_map(|_| 0.5f64.to_le_bytes())
            .collect();
        std::fs::write(&bin_path, &data).unwrap();

        let checksum = checksum_bytes(&data);
        let manifest = serde_json::json!({
            "artifact_type":    "emergency_range_prior",
            "version":           1u32,
            "checksum_sha256":   checksum,
            "file_size_bytes":   data.len() as u64,
            "n_hand_buckets":    N_HAND_BUCKETS,
            "n_board_textures":  N_BOARD_TEXTURES,
            "n_pot_classes":     N_POT_CLASSES,
            "n_aggressor_roles": N_AGGRESSOR_ROLES,
            "n_player_buckets":  N_PLAYER_BUCKETS,
        });
        std::fs::write(&manifest_path, serde_json::to_string_pretty(&manifest).unwrap()).unwrap();

        (dir, bin_path, manifest_path)
    }

    #[test]
    fn load_valid_prior_succeeds() {
        let (_dir, bin, mf) = build_test_prior();
        EmergencyRangePrior::load(&bin, &mf).unwrap();
    }

    #[test]
    fn bad_checksum_fails_hard() {
        let (_dir, bin, mf) = build_test_prior();

        // Corrupt one byte
        let mut data = std::fs::read(&bin).unwrap();
        data[0] ^= 0xFF;
        std::fs::write(&bin, &data).unwrap();

        let err = EmergencyRangePrior::load(&bin, &mf).unwrap_err();
        assert!(matches!(err, PriorLoadError::Integrity(
            artifact_store::IntegrityError::ChecksumMismatch { .. }
        )));
    }

    #[test]
    fn wrong_version_fails() {
        use artifact_store::checksum_bytes;
        let dir = tempdir().unwrap();
        let bin_path = dir.path().join("prior.bin");
        let mf_path  = dir.path().join("prior.manifest.json");

        let data: Vec<u8> = (0..TABLE_LEN).flat_map(|_| 0.5f64.to_le_bytes()).collect();
        std::fs::write(&bin_path, &data).unwrap();

        let manifest = serde_json::json!({
            "artifact_type":    "emergency_range_prior",
            "version":           2u32,   // wrong version
            "checksum_sha256":   checksum_bytes(&data),
            "file_size_bytes":   data.len() as u64,
            "n_hand_buckets":    N_HAND_BUCKETS,
            "n_board_textures":  N_BOARD_TEXTURES,
            "n_pot_classes":     N_POT_CLASSES,
            "n_aggressor_roles": N_AGGRESSOR_ROLES,
            "n_player_buckets":  N_PLAYER_BUCKETS,
        });
        std::fs::write(&mf_path, serde_json::to_string(&manifest).unwrap()).unwrap();

        let err = EmergencyRangePrior::load(&bin_path, &mf_path).unwrap_err();
        assert!(matches!(err, PriorLoadError::Integrity(
            artifact_store::IntegrityError::VersionMismatch { .. }
        )));
    }

    #[test]
    fn lookup_returns_in_range() {
        let (_dir, bin, mf) = build_test_prior();
        let prior = EmergencyRangePrior::load(&bin, &mf).unwrap();

        let v = prior.lookup(
            HandBucket::TopPairGoodKicker,
            BoardTexture::DryRainbow,
            PotClassIdx::Srp,
            AggressorRole::Ip,
            2,
        );
        assert!((0.0..=1.0).contains(&v), "equity {v} out of [0,1]");
    }

    #[test]
    fn all_lookup_combinations_in_range() {
        let (_dir, bin, mf) = build_test_prior();
        let prior = EmergencyRangePrior::load(&bin, &mf).unwrap();

        use engine_core::HandBucket::*;
        let buckets = [Monster, VeryStrong, Strong, StrongTwoPair, WeakTwoPair,
                       Overpair, TopPairGoodKicker, TopPairWeak, WeakPair,
                       StrongDraw, WeakDraw, Air];
        let textures = [BoardTexture::DryRainbow, BoardTexture::DryPaired,
                        BoardTexture::ConnectedRainbow, BoardTexture::FlushdrawBoard,
                        BoardTexture::WetConnected, BoardTexture::Monotone];
        let pots = [PotClassIdx::Limped, PotClassIdx::Srp, PotClassIdx::ThreeBp, PotClassIdx::FourBpOrSqueeze];
        let aggs = [AggressorRole::None, AggressorRole::Ip, AggressorRole::Oop];

        for h in buckets {
            for t in textures {
                for p in pots {
                    for a in aggs {
                        for n in 2u8..=6 {
                            let v = prior.lookup(h, t, p, a, n);
                            assert!((0.0..=1.0).contains(&v));
                        }
                    }
                }
            }
        }
    }

    #[test]
    fn n_players_to_bucket_clamps() {
        assert_eq!(n_players_to_bucket(2), 0);
        assert_eq!(n_players_to_bucket(6), 4);
        assert_eq!(n_players_to_bucket(7), 4); // clamped
        assert_eq!(n_players_to_bucket(1), 0); // clamped
    }

    #[test]
    fn real_artifact_matches_manifest() {
        // This test only runs when the real artifact exists (CI or local after build).
        let repo_root = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent().unwrap().parent().unwrap().parent().unwrap().to_path_buf();
        let bin_path = repo_root.join("artifacts/emergency/emergency_range_prior.bin");
        let mf_path  = repo_root.join("artifacts/emergency/emergency_range_prior.manifest.json");

        if !bin_path.exists() {
            eprintln!("Skipping real_artifact_matches_manifest: artifact not built yet");
            return;
        }

        let prior = EmergencyRangePrior::load(&bin_path, &mf_path).unwrap();

        // Strong hands should have higher equity than air on a dry board in SRP HU
        let monster = prior.lookup(HandBucket::Monster, BoardTexture::DryRainbow, PotClassIdx::Srp, AggressorRole::Ip, 2);
        let air     = prior.lookup(HandBucket::Air,     BoardTexture::DryRainbow, PotClassIdx::Srp, AggressorRole::Ip, 2);
        assert!(monster > air, "Monster ({monster}) should beat Air ({air})");

        // Monotone board should be lower equity for TPGK than dry rainbow
        let tpgk_dry  = prior.lookup(HandBucket::TopPairGoodKicker, BoardTexture::DryRainbow, PotClassIdx::Srp, AggressorRole::None, 2);
        let tpgk_mono = prior.lookup(HandBucket::TopPairGoodKicker, BoardTexture::Monotone,   PotClassIdx::Srp, AggressorRole::None, 2);
        assert!(tpgk_mono < tpgk_dry);
    }
}
